name: Deploy to Local Server

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

jobs:
  build_deploy:
    runs-on: self-hosted

    steps:
      # Шаг 1: Скачиваем свежий код прямо на домашний сервер
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Сборка Docker-образа локально
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag discordchatbot:latest

      # Шаг 3: Остановка старого контейнера
      - name: Stop and remove old container
        run: |
          docker stop dcchatbot || true
          docker rm dcchatbot || true

      # Шаг 4: Запуск нового контейнера с передачей всех нужных переменных окружения
      - name: Run new container
        run: |
          docker run -d --name dcchatbot \
            --restart unless-stopped \
            -v chroma_data:/python-app/chroma_db \
            -e WEATHER_API="${{ secrets.WEATHER_API }}" \
            -e DC_TOKEN="${{ secrets.DC_TOKEN }}" \
            -e SEARCH_API="${{ secrets.SEARCH_API }}" \
            -e AI_TOKEN="${{ secrets.AI_TOKEN }}" \
            -e AI_TOKEN1="${{ secrets.AI_TOKEN1 }}" \
            -e AI_TOKEN_POLZA="${{ secrets.AI_TOKEN_POLZA }}" \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" \
            -e TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -e YOUTUBE_API_KEY="${{ secrets.YOUTUBE_API_KEY }}" \
            discordchatbot:latest

      # Шаг 5: Очистка старых "повисших" образов, чтобы не забивать память
      - name: Clean up unused Docker images
        run: docker image prune -f
